### PR TITLE
Add conversion from Rgb666 and Bgr666 to Grey8

### LINKED ISSUE #654: Add greyscale conversions for Rgb666
I think [this line](https://github.com/embedded-graphics/embedded-graphics/blob/master/core/src/pixelcolor/conversion.rs#L108) is missing `Rgb666` (missed by me when approving #621.

### PR DESCRIPTION
**Pull request by brianmay**
This is required for the tinytga library.

Fixes #654.

### CODE REVIEW

**Review by jamwaffles — APPROVED** [review]
LGTM but I'll let @rfuest merge in case I missed anything with the colour conversion code.

**Review by rfuest — CHANGES_REQUESTED** [review]
The change itself looks good, but there are other instances in the same file where `Rgb666` and `Bgr666` are also missing. At least the `gray_to_rgb` and `rgb_to_gray` should be fixed before this gets merged.

The `impl_from_binary!` and `impl_rgb_to_binary!` and their test are also missing the `Rgb666` and `Bgr666` types. But if you don't want to fix these now, because they are outside the scope of this PR, we can fix these later.

**Comment by brianmay** [comment]
I am totally unfamiliar with this code, so not surprising if I missed something.

Looks like I missed updating the tests. Tests are good. Now fixed. Hopefully.

**Comment by brianmay** [comment]
For some reason the CI is unahppy with my new references to `Bgr666`. Don't understand why, all the tests pass on my box.

This is something  I might need help with.

**Comment by rfuest** [comment]
> For some reason the CI is unahppy with my new references to `Bgr666`. Don't understand why, all the tests pass on my box.

Maybe you forgot to commit something? `Rgb666` and `Bgr666` are missing in the invocations of the `impl_from_binary!` (line 121` and `impl_rgb_to_binary!` (line 147) macros.

**Comment by brianmay** [comment]
I missed those places. Now fixed. Odd this didn't break the tests when I ran them locally.

**Comment by brianmay** [comment]
Tests pass now.

**Comment by rfuest** [comment]
> Odd this didn't break the tests when I ran them locally.

Did you run the tests by calling `cargo test`? Because that only runs the tests in the main `embedded-graphics` crate and not the `embedded-graphics-core` crate. You need to run `cargo test --workspace` or preferably use `just build` (if you aren't using Windows) to run all tests.

**Pull request merged**
