### PR TITLE
Add `u8g2-fonts` external crate

### PR DESCRIPTION
**Pull request by Finomnis**
Add external crate `u8g2-fonts` to `README` and the `lib.rs` documentation.

### CODE REVIEW

**Comment by rfuest** [comment]
In it's current state `u8g2-fonts` isn't integrated with e-g's text rendering. Calling `u8g2-fonts` a collection of fonts might be misleading.

**Comment by Finomnis** [comment]
I agree. Let's talk about integration. (https://github.com/embedded-graphics/embedded-graphics/issues/686)

**Comment by Finomnis** [comment]
Until then, I added a note that makes it clear that this is an external font renderer.

**Review by rfuest — APPROVED** [review]

**Comment by rfuest** [comment]
LGTM. @jamwaffles will need to merge this, because of the unrelated CI issue.

**Comment by jamwaffles** [comment]
Thanks!

**Comment by Finomnis** [comment]
Just wanted to say wait, I'm currently working on connecting it to the current Text renderer, but too late :D

**Comment by jamwaffles** [comment]
No worries, nothing is released yet (and won't be for a while) so if you'd like to change the description just open another PR :)

**Pull request merged**
