### PR TITLE
Rename all to iter

### PR DESCRIPTION
**Pull request by bugadani**
Thank you for helping out with embedded-graphics development! Please:

- [ ] Check that you've added passing tests and documentation
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) if your changes affect the **public API**
- [ ] Run `rustfmt` on the project
- [ ] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

As discussed in https://github.com/embedded-graphics/embedded-graphics/pull/596#discussion_r642083109

### CODE REVIEW

**Comment by bugadani** [comment]
@rfuest is the associated function used anywhere?

**Comment by rfuest** [comment]
> @rfuest is the associated function used anywhere?

Yes, but not in e-g itself. It's used in the new font conversion tool.

**Comment by rfuest** [comment]
@jamwaffles How should we handle this breaking change? I don't think it requires a new beta release on its own, because only a very limited set of other crates will depend on this API.

**Comment by jamwaffles** [comment]
I agree, I think it's fine to release it with other work. It's also trivial to update code to use the new name, so the impact is low for a breaking change.

Also, congratulations to us on 600 PRs/issues :tada:!

**Comment by bugadani** [comment]
I'm a bit ashamed the 600th wasn't something bigger, to be honest 😅

**Review by rfuest — APPROVED** [review]

**Comment by jamwaffles** [comment]
I'll be posting people cake when we hit #1000 so make it worth it ;)

**Comment by rfuest** [comment]
> I'll be posting people cake when we hit #1000 so make it worth it ;)

Don't tempt us or you'll need to review a lot of very small PRs in the near future :wink:.

**Comment by bugadani** [comment]
Nah I bet the cake is a lie.

**Pull request merged**
