### PR TITLE
Rename ImagePixelGetter to GetPixel

### PR DESCRIPTION
**Pull request by rfuest**
This PR renames the pixel getter as discussed in #696.

### CODE REVIEW

**Comment by rfuest** [comment]
Is there a better place to put this trait than the `image` module, now that it isn't used exclusively for images?

**Review by jamwaffles — APPROVED** [review]
lgtm

> Is there a better place to put this trait than the image module, now that it isn't used exclusively for images?

That is an excellent question. It doesn't quite fit with `image` any more but I can't think of a better place to put it. Maybe we could generalise the image/framebuffer/pixel getter stuff into a newly named module? I can't think of a name for that either... `SquareStuffWithPixels` doesn't exactly roll off the toungue.

**Comment by rfuest** [comment]
> `SquareStuffWithPixels` doesn't exactly roll off the toungue.

That would be the perfect name, but unfortunately the trait could also be used for non square stuff :wink: 

The only other place that would fit IMO is the crate root, but the trait might not be important enough to deserve the honor of being there.

**Comment by jamwaffles** [comment]
> unfortunately the trait could also be used for non square stuff 

I spent a long time and all of my sponsorship money on a focus group for that name. What a waste :(

> The only other place that would fit IMO is the crate root, but the trait might not be important enough to deserve the honor of being there.

I agree. It seems the best place for `GetPixel` is in `image`, for now at least.

**Pull request merged**
