### PR TITLE
Move DrawTargetExt and adapters from core to e-g

### PR DESCRIPTION
**Pull request by rfuest**
Thank you for helping out with embedded-graphics development! Please:

- [ ] Check that you've added passing tests and documentation
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) if your changes affect the **public API**
- [ ] Run `rustfmt` on the project
- [ ] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

This PR moves `DrawTargetExt` and the draw target adapters, like `Cropped` and `Translated`, from `core` to `e-g`. IMO they don't need to be included in `core`, because the aren't part of the image, font or display APIs.

The reason these were included in the first place was the default impl of `draw_sub_image` in `ImageDrawable`. This PR removes the default impl, so that each image format crate will need to implement this method separately. I think this is a reasonable compromise to keep the core crate small. `tinybmp` and `tinytga` will need to depend on e-g instead of core to implement this feature, but they should still be compatible across different e-g versions, because all types in the `ImageDrawables` are included in `core`.

### CODE REVIEW

**Review by jamwaffles — CHANGES_REQUESTED** [review]
It's a shame to break core so early, but nobody is using it so that's fine.

Looks good to me apart from any necessary changelog items for core and e-g.

To confirm, once merged I'll:

* Release core 0.2.0
* Release e-g 0.7.0-alpha.3

The simulator, tinytga and tinybmp will all need new alphas as well once the above is done.

**Comment by rfuest** [comment]
> It's a shame to break core so early, but nobody is using it so that's fine.

This change is part of #505 and we had discussed the breaking changes in the core crate in the linked discussion https://github.com/embedded-graphics/embedded-graphics/pull/498#pullrequestreview-540484691.

Regarding the changelog entries: Does e-g need an entry for this change, because the API didn't change? The e-g changelog doesn't mention the core split at all. We should probably start to document the compatibility of e-g and e-g-core versions at some point, but that's outside the scope of this PR.

**Comment by rfuest** [comment]
> To confirm, once merged I'll:
> 
> * Release core 0.2.0
>  * Release e-g 0.7.0-alpha.3

Would it be better to wait until #505 is finished?

**Review by jamwaffles — APPROVED** [review]
> Does e-g need an entry for this change, because the API didn't change?

No, that changelog can be left alone.

> Would it be better to wait until #505 is finished?

Ah yes, it would. It's been a while since I went through the issues again.

**Pull request merged**
