### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by bugadani**
Thank you for helping out with embedded-graphics development! Please:

- [x] Check that you've added passing tests and documentation
- [x] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) if your changes affect the **public API**
- [x] Run `rustfmt` on the project
- [x] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

This PR fixes a few typos and clippy warnings. This PR also excludes defmt from the MSRV guarantees because the crate itself doesn't guarantee anything beyond "latest stable".

### CODE REVIEW

**Comment by bugadani** [comment]
how did that check fail here but not on previous PRs?

**Comment by bugadani** [comment]
CI is failing because of defmt-parse. How should we approach this?

**Comment by rfuest** [comment]
> CI is failing because of defmt-parser which has a "latest stable" MSRV. How should we approach this?

The only solution I can think of is to remove the `defmt` feature from all MSRV builds. I've created a PR to remove the feature: https://github.com/embedded-graphics/embedded-graphics/pull/724
At the momement CI still fails because the new `tinytga` version hasn't been published yet.

**Comment by bugadani** [comment]
I tried doing that but I couldn't figure out how the justfile works 😅

**Comment by rfuest** [comment]
> I tried doing that but I couldn't figure out how the justfile works sweat_smile

The justfile could use some cleanup, but I think the CI docker file still uses an ancient version of just, which would need to be updated first to use some of the newer just features.

**Pull request merged**
