### PR TITLE
Upgrade to Rust 1.47

### PR DESCRIPTION
**Pull request by jamwaffles**
Hi! Thank you for helping out with Embedded Graphics development! Please:

- [ ] Check that you've added passing tests and documentation
- [ ] Add a simulator example(s) where applicable
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) and appropriate crate (`embedded-graphics`, `simulator`, `tinytga`, `tinybmp`) if your changes affect the **public API**
- [ ] Run `rustfmt` on the project
- [ ] Run `just build` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

[add your PR description here]

### CODE REVIEW

**Comment by jamwaffles** [comment]
This isn't really giving us much. Performance is a mixed bag but is largely the same and we still can't `const` lots of things. I'd be tempted to close this and wait until there's a more compelling time to upgrade, as somewhat old as 1.40 is.

**Comment by rfuest** [comment]
`embedded-fonts` needs some newer proc-macro features, which were introduced in 1.44, if I remember correctly. Should we only require a newer rust version for that crate or use the same MSRV for all crates?

**Comment by jamwaffles** [comment]
>  Should we only require a newer rust version for that crate or use the same MSRV for all crates?

Only for that crate, if possible - that way users who don't want `embedded-fonts` don't need to use a recent version of Rust if they don't want to/can't.

**Comment by rfuest** [comment]
OK, but this means that we will also need to maintain multiple versions of the docker image.

**Comment by jamwaffles** [comment]
I think that's ok as each project can evolve separately that way. 

We could move the relevant bits of the `just` Docker build/push commands and CircleCI config changes in e-g into `embedded-fonts` and get it using its own Docker image. I'm happy to do that if you don't want to.

**Comment by rfuest** [comment]
> We could move the relevant bits of the `just` Docker build/push commands and CircleCI config changes in e-g into `embedded-fonts` and get it using its own Docker image. I'm happy to do that if you don't want to.

Or we could create a new repo in the e-g org to contain all docker related files. IMO that would make it easier to maintain than having docker related files spread across multiple repos.

**Comment by jamwaffles** [comment]
Good shout. Is any of this a blocker to the actual e-f work that needs doing?

**Comment by rfuest** [comment]
No, we can work on CI for e-f when it is added to the org.

**Comment by jamwaffles** [comment]
Closing, see #463 for build tools tracking.

**Pull request closed without merging**
